# Generated by Django 5.2.4 on 2025-08-19 20:32

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created Date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='products', variations={'thumb': (124, 124)}, verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
